# Generated by Django 3.1.6 on 2021-11-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=2000)),
            ],
        ),
    ]
