# Generated by Django 3.1.6 on 2021-12-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_note_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='birthday',
            field=models.DateField(default=None),
        ),
    ]
